name: Lint Emacs

on:
  push:
    paths: ['**.el']
  pull_request:
    paths: ['**.el']

jobs:
  test:
    runs-on: ubuntu-latest
    # continue-on-error: ${{matrix.emacs_version == 'snapshot'}}

    strategy:
      matrix:
        emacs_version: ['snapshot']

    steps:
    - name: Set up Emacs
      uses: purcell/setup-emacs@master
      with:
        version: ${{matrix.emacs_version}}

    - name: Install Eldev
      run: curl -fsSL https://raw.github.com/doublep/eldev/master/webinstall/github-eldev | sh

    - name: Check out the source code
      uses: actions/checkout@v2

    - name: Lint the project
      run: eldev -dtT -C compile --warnings-as-errors
